name: safeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  permission_handler: ^11.0.1
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.0.0
  device_apps: ^2.2.0
  android_intent_plus: ^5.3.0
  introduction_screen: ^3.1.17
  local_auth: ^2.3.0
  device_info_plus: ^11.3.0
  http: ^1.3.0
  usage_stats: ^1.3.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"