// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tnURxjBdERUJqnJF1K0eTNgBxNqF0oo',
    appId: '1:480268836668:web:5295ebe4f93317ccab0839',
    messagingSenderId: '480268836668',
    projectId: 'safeapp-51084',
    authDomain: 'safeapp-51084.firebaseapp.com',
    storageBucket: 'safeapp-51084.firebasestorage.app',
    measurementId: 'G-S3V3FNVQ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjxtzIg3Oh19r8WZaRhPxj1RVu259iQXw',
    appId: '1:480268836668:android:7a951a47e0617529ab0839',
    messagingSenderId: '480268836668',
    projectId: 'safeapp-51084',
    storageBucket: 'safeapp-51084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkoK7NyvNZFoDpGqmEf72dDMy2kK6RSSw',
    appId: '1:480268836668:ios:66ad8699da61bbe8ab0839',
    messagingSenderId: '480268836668',
    projectId: 'safeapp-51084',
    storageBucket: 'safeapp-51084.firebasestorage.app',
    iosBundleId: 'com.example.safeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkoK7NyvNZFoDpGqmEf72dDMy2kK6RSSw',
    appId: '1:480268836668:ios:66ad8699da61bbe8ab0839',
    messagingSenderId: '480268836668',
    projectId: 'safeapp-51084',
    storageBucket: 'safeapp-51084.firebasestorage.app',
    iosBundleId: 'com.example.safeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tnURxjBdERUJqnJF1K0eTNgBxNqF0oo',
    appId: '1:480268836668:web:89c5a649f5d0c649ab0839',
    messagingSenderId: '480268836668',
    projectId: 'safeapp-51084',
    authDomain: 'safeapp-51084.firebaseapp.com',
    storageBucket: 'safeapp-51084.firebasestorage.app',
    measurementId: 'G-0243YS25ZQ',
  );
}
